application: gaecmsproject
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 )$

handlers:
- url: /favicon.ico
  static_files: media/images/favicon.ico
  upload: media/images/favicon.ico
  mime_type: image/x-icon 

- url: /tiny_mce/.*
  script: $PYTHON_LIB/google/appengine/ext/zipserve

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /media
  static_dir: media
  secure: optional

- url: /.*
  script: common/appenginepatch/main.py
  secure: optional
